"""修改cars model

Revision ID: 6b9e1a58e464
Revises: 8c156cd74b3f
Create Date: 2025-06-23 03:14:11.415828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b9e1a58e464'
down_revision = '8c156cd74b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('displacement')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('displacement', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))

    # ### end Alembic commands ###
