"""修改修改cars

Revision ID: 8c156cd74b3f
Revises: d6eb5cf5eec4
Create Date: 2025-06-23 02:41:11.505031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c156cd74b3f'
down_revision = 'd6eb5cf5eec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exterior_color', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('interior_color', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('engine', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fuel_economy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transmission', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('drive', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('luggage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mileage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('mileage')
        batch_op.drop_column('luggage')
        batch_op.drop_column('drive')
        batch_op.drop_column('transmission')
        batch_op.drop_column('fuel_economy')
        batch_op.drop_column('engine')
        batch_op.drop_column('interior_color')
        batch_op.drop_column('exterior_color')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
