"""修改 Car 資料表欄位按照範例

Revision ID: ca6c4d61267d
Revises: cbee8901dcb4
Create Date: 2025-06-28 18:52:55.112842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca6c4d61267d'
down_revision = 'cbee8901dcb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('displacement', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('car_type', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=255), nullable=True))
        batch_op.drop_column('interior_color')
        batch_op.drop_column('exterior_color')
        batch_op.drop_column('fuel_economy')
        batch_op.drop_column('transmission')
        batch_op.drop_column('luggage')
        batch_op.drop_column('drive')
        batch_op.drop_column('mileage')
        batch_op.drop_column('year')
        batch_op.drop_column('engine')
        batch_op.drop_column('vehicle_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.add_column(sa.Column('engine', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mileage', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('drive', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('luggage', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transmission', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('fuel_economy', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('exterior_color', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('interior_color', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('model')
        batch_op.drop_column('car_type')
        batch_op.drop_column('displacement')

    # ### end Alembic commands ###
