"""Add created_at and created_by to CarImages

Revision ID: 28175dc7ecb4
Revises: 8219527d5eee
Create Date: 2025-08-05 11:41:01.559771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28175dc7ecb4'
down_revision = '8219527d5eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
