"""add popular_cars table

Revision ID: 51888bce30eb
Revises: 8d3b31864693
Create Date: 2025-08-08 15:01:50.217779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51888bce30eb'
down_revision = '8d3b31864693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('popular_cars')
    # ### end Alembic commands ###
