"""修改cars table

Revision ID: 60f92defb954
Revises: 23c9db5d386e
Create Date: 2025-08-07 17:14:31.797912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60f92defb954'
down_revision = '23c9db5d386e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))

    # ### end Alembic commands ###
