"""Add vehicle_type to Car

Revision ID: cbee8901dcb4
Revises: 6b9e1a58e464
Create Date: 2025-06-23 03:35:21.763312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbee8901dcb4'
down_revision = '6b9e1a58e464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type', sa.String(length=255), nullable=False))
        batch_op.drop_column('car_type')
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('car_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.drop_column('vehicle_type')

    # ### end Alembic commands ###
