"""Recreate migrations

Revision ID: d6eb5cf5eec4
Revises: 
Create Date: 2025-06-22 22:24:49.605728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6eb5cf5eec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('door', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('displacement', sa.String(length=255), nullable=False),
    sa.Column('car_type', sa.String(length=255), nullable=False),
    sa.Column('seat_number', sa.String(length=255), nullable=False),
    sa.Column('door_number', sa.String(length=255), nullable=False),
    sa.Column('car_length', sa.String(length=255), nullable=False),
    sa.Column('wheelbase', sa.String(length=255), nullable=False),
    sa.Column('power_type', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('cars')
    # ### end Alembic commands ###
